### ISSUE TITLE
How to keep accurate bot list maintained?

### ISSUE THREAD

**Issue by niftylettuce** [gorangajic/isbot#15]
Perhaps use/scrape this with cheerio?

https://www.distilnetworks.com/bot-directory/category/search-engine/

**Comment by gorangajic** [comment]
I am open to pull request that will automate that

**Comment by omrilotan** [comment]
I'd be happy to add automation. However, I could not find a free user agent database yet. If you have any suggestions - I would be happy to pick it up from there.

**Comment by maximn** [comment]
What about using rules/regex instead of a static list?

**Comment by omrilotan** [comment]
@maximn We are using rules and regex. I think the issue is to get updated lists of user agents to test against

**Comment by omrilotan** [comment]
Maintenance workflow added in #47 

> ## [Add periodic tests](https://github.com/gorangajic/isbot/pull/47)
> - NPM prepare (runs after install) downloads a user agent list from [monperrus/crawler-user-agents](https://github.com/monperrus/crawler-user-agents)
> - Tests run
> - If tests fail - an issue is created
> 
> Since user agent databases are costly - I'm going to try to work with this open source repository for now

![](https://user-images.githubusercontent.com/516342/67942134-d61cc800-fbdf-11e9-9250-3a8ffceed02d.png)

**Comment by omrilotan** [comment]
Re created the same scheduled pipeline (cronjob) in CircleCI

![](https://user-images.githubusercontent.com/516342/74379721-fbc98800-4df0-11ea-94d4-d5ed0263fd7d.png)

**Comment by omrilotan** [comment]
I feel we made good progress on [version 3](https://github.com/gorangajic/isbot/releases/tag/v3.0.0) with two dynamic bot lists. Seems good enough for now
