### ISSUE TITLE
Is this library intended to be used in a browser with webpack?

### ISSUE THREAD

**Issue by piotr-sobczyk** [gorangajic/isbot#21]
The library is called: "*Node.js module* that detects bots/crawlers/spiders via the user agent". Does it imply that it's suited to node.js environment only?

We were able to successfully use it the browser with Webpack. Was it intended to be used this way too? Do you know some potential pitfalls? Is it safe to use it way on production?

**Comment by gorangajic** [comment]
It should work fine in a browser, don't see a problem with that
