### ISSUE TITLE
Performance Improvement

### ISSUE THREAD

**Issue by natanavra** [gorangajic/isbot#22]
RegEx is very slow
Consider iterating through the bot list with a `for` loop 
Here's a jsperf:
https://jsperf.com/user-agent-filter-regex-vs-indexof/1

**Comment by gorangajic** [comment]
Your test case is initializing `new RegExp` on every test, that's why it's slower.
I have created a new test case that moves initialization on setup and it's faster than `indexOf`.


https://jsperf.com/regex-index-of-2
