### ISSUE TITLE
Add Google PageSpeed Insights

### ISSUE THREAD

**Issue by mhluska** [gorangajic/isbot#24]
Should this include the user agent for Google PageSpeed?

See https://stackoverflow.com/questions/16403295/what-is-the-name-of-the-google-pagespeed-user-agent

The user agent: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; Google Page Speed Insights) Chrome/27.0.1453 Safari/537.36`

Google PageSpeed Insights: https://developers.google.com/speed/pagespeed/insights

**Comment by gorangajic** [comment]
Sure can you make a pull request?
