### ISSUE TITLE
Wrong detect

### ISSUE THREAD

**Issue by hogvarce** [gorangajic/isbot#26]
Not correctly identifies the user agent

 Mozilla/5.0 (Linux; Android 8.1.0; Mi A1 Build / OPM1.171019.026; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version / 4.0 Chrome/68.0.3440.91 Mobile Safari/537.36 YandexSearch/7.71 YandexSearchBrowser/7.71

thinks it's a bot

**Comment by hogvarce** [comment]
When you go with Android 
Mozilla/5.0 (Linux; Android 7.0; SM-T585 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) version / 4.0 Chrome/56.0.2924.87 Safari/537.36 YandexSearch/7.71 / apad YandexSearchBrowser/7.71
defines how the bot

**Comment by gorangajic** [comment]
I am busy and not sure when I can fix this. Can you submit a pull request that handles that case?

**Comment by knoxcard** [comment]
I see the issue, Yandex has a browser "YandexSearchBrowser".  Would just need to insert that particular rule.

**Comment by omrilotan** [comment]
Fixed before, bud addressed in commit 76a27f6
