### ISSUE TITLE
Wrong detect Cubot devices

### ISSUE THREAD

**Issue by goldip** [gorangajic/isbot#29]
Hey,

your script isn't capable of detecting Cubot devices - it's probably a "bot" string in the name. I'm sending several user agents for testing:

```
Mozilla/5.0 (Linux; Android 8.0.0; CUBOT_P20) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 8.1.0; CUBOT_POWER) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 8.0.0; CUBOT_X18_Plus Build/O00623; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.99 Mobile Safari/537.36 OPR/37.6.2254.134291
Mozilla/5.0 (Linux; Android 6.0; CUBOT_NOTE_S) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.80 Mobile Safari/537.36
```

**Comment by Niffy** [comment]
We are having similar issues.
It would be nice if there was a whitelist function, similar to the extend function. Then adding in a workaround would be pretty simple.

**Comment by gorangajic** [comment]
I am open to pull requests that will handle this use case

**Comment by omrilotan** [comment]
@goldip @Niffy Would you consider #35 a solution to your issue?

**Comment by omrilotan** [comment]
Addressed in 35
