### ISSUE TITLE
Detecting Social Bots?

### ISSUE THREAD

**Issue by knoxcard** [gorangajic/isbot#30]
What about detecting Facebook, Twitter and LinkedIn?

They ping your site when you post links on their platforms.
Then read your social meta tags that you provide.

isSocial()?

My workaround...
```
var ua = require('useragent')
ua(true)
req.session.userAgent = ua.lookup(req.headers['user-agent'])
var ua = req.session.userAgent.toString().toLowerCase()
isSocialBot: (ua.indexOf('facebook') > -1 || ua.indexOf('twitter') > -1 || ua.indexOf('linkedin') > -1) ? true : false
```

Needed to do this recently to hide/show social html meta data in my header tag...
```
{{#if isSocialBot}}
<meta property="og:site_name" content="" />
<meta property="og:title" content="" />
<meta property="og:image" content="" />
<meta property="og:url" content="" />
<meta property="og:type" content="website" />
<meta property="og:locale" content="en_US" />
<meta property="og:locale:alternate" content="en_CA" />
<meta property="og:locale:alternate" content="fr_CA" />
{{/if}}
```

**Comment by omrilotan** [comment]
I feel like classification of user agents is outside the scope of this module.
`isbot` is a single use module. It allows it to remain simple and quick.

I vote for dismissing this one as a `wontfix`, any rejections?

**Comment by knoxcard** [comment]
I agree! I'll close the issue.
