### ISSUE TITLE
Typescrit types are broken

### ISSUE THREAD

**Issue by johannessteu** [gorangajic/isbot#45]
This one https://github.com/gorangajic/isbot/commit/17338c24d60bd24c4d5eb713bad3ab8368f51a4d should actually fix ts definitions. But it broke it for me. As soon as i build my app it end's up in something like this:

```
$ NODE_ENV=production tsc
node_modules/isbot/index.d.ts:19:1 - error TS1036: Statements are not allowed in ambient contexts.

19 testUserAgent.extend = extend;
```

Here is a codesandbox to reproduce the issue (run the build script):

https://codesandbox.io/s/async-tree-lxpjv?expanddevtools=1&fontsize=14&hidenavigation=1&moduleview=1

If i downgrade to 2.4.0 it's finde for me

**Comment by omrilotan** [comment]
Solved in version 2.5.0
