### ISSUE TITLE
Bug - user agent incorrectly treated as a bot

### ISSUE THREAD

**Issue by doitadrian** [gorangajic/isbot#51]
Thanks for the lib @gorangajic.

I think I found a bug, or at least it looks to me like it is a bug.

I'm making a request from a Lambda function using `chrome-aws-lambda` lib. 
Below we can see which User-Agent it sets (`UA_LAMBDA`).

Once I pass this value to the `isbot`, it returns `true`, but this is not a bot obviously.

```js
var isbot = require("isbot");

const UA_LAMBDA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/79.0.3945.0 Safari/537.36";
const UA_CHROME_MAC =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36";

console.log(isbot(UA_LAMBDA)); // true
console.log(isbot(UA_CHROME_MAC)); // false
```
Is this a bug?

When I execute the same request from an ordinary Chrome, it all works good (`UA_CHROME_MAC`).

Feel free to correct me if I said anything incorrect.

Thank you!

**Comment by omrilotan** [comment]
Yes, @doitadrian, HeadlessChrome is explicitly considered a bot by `isbot`.
I think its definition matches the behaviour usually associated with bots. It is not used by people to visit sites but by automated processes.

> [A headless browser is a great tool for automated testing and server environments](https://developers.google.com/web/updates/2017/04/headless-chrome)

**Comment by omrilotan** [comment]
By the way, if you wish not to identify yourself as a headless browser - usually used for automated tasks - Puppeteer (the browser used by `chrome-aws-lambda`) can be configured to run full (non-headless) Chrome or Chromium.
```js
const chromium = require('chrome-aws-lambda');

...
browser = await chromium.puppeteer.launch({
  headless: false
})
...
```

**Comment by doitadrian** [comment]
Very nice @omrilotan, thanks for the info!

I actually overrode UA and then it worked nicely:
```
await page.setExtraHTTPHeaders({ "User-Agent": "chrome-aws-lambda" });
```

Gonna close this one.

Thanks again!
