### ISSUE TITLE
Empty user agent strings

### ISSUE THREAD

**Issue by sebranly** [gorangajic/isbot#66]
Nice project, thanks for sharing it!

What's your take on empty user agent strings? (`''`)
It seems like they are being considered as not a bot currently, what about considering them as a bot instead?

**Comment by omrilotan** [comment]
This package explicitly checks is a user agent string identifies as bot - usually crawlers. I don't know if not matching any would count as "identifying as a bot". Can you explain why you think it would? Have you seen any traffic w/o a user agent header which is a bot?

**Comment by sebranly** [comment]
I think there's no definite answer on how to classify an empty user agent string. I haven't seen any such case so it's more of an opinion really. I think my point of view is that if the user agent doesn't get sent, then either it's a bot, or it's a human who willingly decided to remove the user agent from the headers, so they shouldn't be surprised if they are being classified as a bot.

That's just my 2 cents on it, based on reading a few articles/answers on the web e.g. https://webmasters.stackexchange.com/questions/35642/interpretation-of-empty-user-agent. Both work for me but I was curious about your take on this as you invested time developing this package

**Comment by omrilotan** [comment]
@sebranly I'll give it a read 👌

**Comment by omrilotan** [comment]
@sebranly Thank you, that was an excellent point. I think it one of the notions in that thread was referring to both attempts:
- Identify humans
- Identify bots

This library is not attempting to identify humans, rather identify user agents who belong to known bots. As such, the question it asks is: "Does this user agent belong to a known bot"? And an empty string can not answer this question and I think can not be true.

However - based on your use case you can modify the behaviour of this package:

```js
isBot('') // false
isBot.extend(['^$'])
isBot('') // true
```

In my opinion that should be the resolution for your case.

**Comment by sebranly** [comment]
That makes perfect sense to me with this specific goal of "identifying known bots" 👍 
To be fair, as my use case makes me want to consider an empty user agent string as a bot (slightly different use case than yours), I was using the `isBot` package by wrapping it up.

Something like
```ts
const isBotUA = (userAgent: string) => {
  if (userAgent === '') return true;
  isBot.extend(UA_BOTS_KEYWORDS);
  return isBot(userAgent);
};
```

But I just tested your suggestion (with a custom unit test suite supporting some well-known user agents) and it works as well with the regex directly added to `UA_BOTS_KEYWORDS` 👍 
Thank you for the conversation on this one and for the package! By the way one major point that convinced me to use your package was the PR about https://support.google.com/webmasters/answer/1061943?hl=en
