### ISSUE TITLE
QUESTION: "bot" in list.json seems too permissive?

### ISSUE THREAD

**Issue by stevenolay** [gorangajic/isbot#83]
I noticed that "bot" is one of the keywords and it greedy matches for any user agent containing those 3 characters in a row. I feel like this is great for capturing user agents like:

Slackbot 1.0(+https://api.slack.com/robots)
Slackbot-LinkExpanding 1.0 (+https://api.slack.com/robots)

However, it feels too permissive. Is it a fair assumption that there are no legitimate user agents that could contain the characters bot?

This is more of a question than an issue. Just curious on the thinking there.

 I am also assuming that out of the 3 bot user agent listings used  to construct the list.json that the regex(s) chosen are intended to cover all of the user agents listed but are not one to one?

**Comment by omrilotan** [comment]
I don't want to leave this legitimate question hanging, so I'll address it.

We add real user agents to test by both manual list and using [npm "user-agents" package](https://www.npmjs.com/package/user-agents) to verify we do not misidentify browser user-agent strings.

We try to find common denominators to reduce the complexity of the RegEx pattern and improve runtime (bot, crawl, spider, feed, google).
